// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _hls_divider_HH_
#define _hls_divider_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "hls_divider_udiv_bkb.h"
#include "hls_divider_urem_cud.h"
#include "hls_divider_CRTLS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_CRTLS_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_CRTLS_DATA_WIDTH = 32>
struct hls_divider : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > s_axi_CRTLS_AWVALID;
    sc_out< sc_logic > s_axi_CRTLS_AWREADY;
    sc_in< sc_uint<C_S_AXI_CRTLS_ADDR_WIDTH> > s_axi_CRTLS_AWADDR;
    sc_in< sc_logic > s_axi_CRTLS_WVALID;
    sc_out< sc_logic > s_axi_CRTLS_WREADY;
    sc_in< sc_uint<C_S_AXI_CRTLS_DATA_WIDTH> > s_axi_CRTLS_WDATA;
    sc_in< sc_uint<C_S_AXI_CRTLS_DATA_WIDTH/8> > s_axi_CRTLS_WSTRB;
    sc_in< sc_logic > s_axi_CRTLS_ARVALID;
    sc_out< sc_logic > s_axi_CRTLS_ARREADY;
    sc_in< sc_uint<C_S_AXI_CRTLS_ADDR_WIDTH> > s_axi_CRTLS_ARADDR;
    sc_out< sc_logic > s_axi_CRTLS_RVALID;
    sc_in< sc_logic > s_axi_CRTLS_RREADY;
    sc_out< sc_uint<C_S_AXI_CRTLS_DATA_WIDTH> > s_axi_CRTLS_RDATA;
    sc_out< sc_lv<2> > s_axi_CRTLS_RRESP;
    sc_out< sc_logic > s_axi_CRTLS_BVALID;
    sc_in< sc_logic > s_axi_CRTLS_BREADY;
    sc_out< sc_lv<2> > s_axi_CRTLS_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    hls_divider(sc_module_name name);
    SC_HAS_PROCESS(hls_divider);

    ~hls_divider();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    hls_divider_CRTLS_s_axi<C_S_AXI_CRTLS_ADDR_WIDTH,C_S_AXI_CRTLS_DATA_WIDTH>* hls_divider_CRTLS_s_axi_U;
    hls_divider_udiv_bkb<1,20,16,16,16>* hls_divider_udiv_bkb_U1;
    hls_divider_urem_cud<1,20,16,16,16>* hls_divider_urem_cud_U2;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<20> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<16> > a;
    sc_signal< sc_lv<16> > b;
    sc_signal< sc_lv<32> > ap_return;
    sc_signal< sc_lv<16> > grp_fu_36_p2;
    sc_signal< sc_lv<16> > grp_fu_42_p2;
    sc_signal< sc_logic > ap_CS_fsm_state20;
    sc_signal< sc_logic > grp_fu_36_ap_start;
    sc_signal< sc_logic > grp_fu_36_ap_done;
    sc_signal< sc_logic > grp_fu_42_ap_start;
    sc_signal< sc_logic > grp_fu_42_ap_done;
    sc_signal< sc_lv<20> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<20> ap_ST_fsm_state1;
    static const sc_lv<20> ap_ST_fsm_state2;
    static const sc_lv<20> ap_ST_fsm_state3;
    static const sc_lv<20> ap_ST_fsm_state4;
    static const sc_lv<20> ap_ST_fsm_state5;
    static const sc_lv<20> ap_ST_fsm_state6;
    static const sc_lv<20> ap_ST_fsm_state7;
    static const sc_lv<20> ap_ST_fsm_state8;
    static const sc_lv<20> ap_ST_fsm_state9;
    static const sc_lv<20> ap_ST_fsm_state10;
    static const sc_lv<20> ap_ST_fsm_state11;
    static const sc_lv<20> ap_ST_fsm_state12;
    static const sc_lv<20> ap_ST_fsm_state13;
    static const sc_lv<20> ap_ST_fsm_state14;
    static const sc_lv<20> ap_ST_fsm_state15;
    static const sc_lv<20> ap_ST_fsm_state16;
    static const sc_lv<20> ap_ST_fsm_state17;
    static const sc_lv<20> ap_ST_fsm_state18;
    static const sc_lv<20> ap_ST_fsm_state19;
    static const sc_lv<20> ap_ST_fsm_state20;
    static const sc_lv<32> ap_const_lv32_0;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_13;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state20();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_ap_rst_n_inv();
    void thread_grp_fu_36_ap_start();
    void thread_grp_fu_42_ap_start();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
