<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="15">
  <syndb class_id="0" tracking_level="0" version="0">
    <userIPLatency>-1</userIPLatency>
    <userIPName/>
    <cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
      <name>hls_divider</name>
      <ret_bitwidth>32</ret_bitwidth>
      <ports class_id="2" tracking_level="0" version="0">
        <count>2</count>
        <item_version>0</item_version>
        <item class_id="3" tracking_level="1" version="0" object_id="_1">
          <Value class_id="4" tracking_level="0" version="0">
            <Obj class_id="5" tracking_level="0" version="0">
              <type>1</type>
              <id>1</id>
              <name>a</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo class_id="6" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>a</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>16</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs class_id="7" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_2">
          <Value>
            <Obj>
              <type>1</type>
              <id>2</id>
              <name>b</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>b</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>16</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
      </ports>
      <nodes class_id="8" tracking_level="0" version="0">
        <count>6</count>
        <item_version>0</item_version>
        <item class_id="9" tracking_level="1" version="0" object_id="_3">
          <Value>
            <Obj>
              <type>0</type>
              <id>7</id>
              <name>b_read</name>
              <fileName>hls_divider/hls_divider.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>1</lineNumber>
              <contextFuncName>hls_divider</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="10" tracking_level="0" version="0">
                  <first>C:\FPGAJosieVivian\HLS_Divider</first>
                  <second class_id="11" tracking_level="0" version="0">
                    <count>1</count>
                    <item_version>0</item_version>
                    <item class_id="12" tracking_level="0" version="0">
                      <first class_id="13" tracking_level="0" version="0">
                        <first>hls_divider/hls_divider.cpp</first>
                        <second>hls_divider</second>
                      </first>
                      <second>1</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>b</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>16</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>18</item>
            <item>19</item>
          </oprand_edges>
          <opcode>read</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>1.00</m_delay>
          <m_topoIndex>1</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_4">
          <Value>
            <Obj>
              <type>0</type>
              <id>8</id>
              <name>a_read</name>
              <fileName>hls_divider/hls_divider.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>1</lineNumber>
              <contextFuncName>hls_divider</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>C:\FPGAJosieVivian\HLS_Divider</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>hls_divider/hls_divider.cpp</first>
                        <second>hls_divider</second>
                      </first>
                      <second>1</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>a</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>16</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>20</item>
            <item>21</item>
          </oprand_edges>
          <opcode>read</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>1.00</m_delay>
          <m_topoIndex>2</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_5">
          <Value>
            <Obj>
              <type>0</type>
              <id>12</id>
              <name>div</name>
              <fileName>hls_divider/hls_divider.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>6</lineNumber>
              <contextFuncName>hls_divider</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>C:\FPGAJosieVivian\HLS_Divider</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>hls_divider/hls_divider.cpp</first>
                        <second>hls_divider</second>
                      </first>
                      <second>6</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>hls_divider_udiv_bkb_U1</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>16</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>22</item>
            <item>23</item>
          </oprand_edges>
          <opcode>udiv</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>3.64</m_delay>
          <m_topoIndex>3</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_6">
          <Value>
            <Obj>
              <type>0</type>
              <id>13</id>
              <name>tmp_2</name>
              <fileName>hls_divider/hls_divider.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>7</lineNumber>
              <contextFuncName>hls_divider</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>C:\FPGAJosieVivian\HLS_Divider</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>hls_divider/hls_divider.cpp</first>
                        <second>hls_divider</second>
                      </first>
                      <second>7</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>hls_divider_urem_cud_U2</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>16</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>24</item>
            <item>25</item>
          </oprand_edges>
          <opcode>urem</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>3.64</m_delay>
          <m_topoIndex>4</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_7">
          <Value>
            <Obj>
              <type>0</type>
              <id>14</id>
              <name>r</name>
              <fileName>hls_divider/hls_divider.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>6</lineNumber>
              <contextFuncName>hls_divider</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>C:\FPGAJosieVivian\HLS_Divider</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>hls_divider/hls_divider.cpp</first>
                        <second>hls_divider</second>
                      </first>
                      <second>6</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>r</originalName>
              <rtlName>ap_return</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>27</item>
            <item>28</item>
            <item>29</item>
          </oprand_edges>
          <opcode>bitconcatenate</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>5</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_8">
          <Value>
            <Obj>
              <type>0</type>
              <id>15</id>
              <name/>
              <fileName>hls_divider/hls_divider.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>10</lineNumber>
              <contextFuncName>hls_divider</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>C:\FPGAJosieVivian\HLS_Divider</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>hls_divider/hls_divider.cpp</first>
                        <second>hls_divider</second>
                      </first>
                      <second>10</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>30</item>
          </oprand_edges>
          <opcode>ret</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>6</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
      </nodes>
      <consts class_id="15" tracking_level="0" version="0">
        <count>0</count>
        <item_version>0</item_version>
      </consts>
      <blocks class_id="16" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="17" tracking_level="1" version="0" object_id="_9">
          <Obj>
            <type>3</type>
            <id>16</id>
            <name>hls_divider</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>6</count>
            <item_version>0</item_version>
            <item>7</item>
            <item>8</item>
            <item>12</item>
            <item>13</item>
            <item>14</item>
            <item>15</item>
          </node_objs>
        </item>
      </blocks>
      <edges class_id="18" tracking_level="0" version="0">
        <count>9</count>
        <item_version>0</item_version>
        <item class_id="19" tracking_level="1" version="0" object_id="_10">
          <id>19</id>
          <edge_type>1</edge_type>
          <source_obj>2</source_obj>
          <sink_obj>7</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="19" object_id="_11">
          <id>21</id>
          <edge_type>1</edge_type>
          <source_obj>1</source_obj>
          <sink_obj>8</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="19" object_id="_12">
          <id>22</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>12</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="19" object_id="_13">
          <id>23</id>
          <edge_type>1</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>12</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="19" object_id="_14">
          <id>24</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>13</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="19" object_id="_15">
          <id>25</id>
          <edge_type>1</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>13</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="19" object_id="_16">
          <id>28</id>
          <edge_type>1</edge_type>
          <source_obj>12</source_obj>
          <sink_obj>14</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="19" object_id="_17">
          <id>29</id>
          <edge_type>1</edge_type>
          <source_obj>13</source_obj>
          <sink_obj>14</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="19" object_id="_18">
          <id>30</id>
          <edge_type>1</edge_type>
          <source_obj>14</source_obj>
          <sink_obj>15</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
      </edges>
    </cdfg>
    <cdfg_regions class_id="20" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="21" tracking_level="1" version="0" object_id="_19">
        <mId>1</mId>
        <mTag>hls_divider</mTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>16</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>19</mMinLatency>
        <mMaxLatency>19</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
    </cdfg_regions>
    <fsm class_id="23" tracking_level="1" version="0" object_id="_20">
      <states class_id="24" tracking_level="0" version="0">
        <count>20</count>
        <item_version>0</item_version>
        <item class_id="25" tracking_level="1" version="0" object_id="_21">
          <id>1</id>
          <operations class_id="26" tracking_level="0" version="0">
            <count>4</count>
            <item_version>0</item_version>
            <item class_id="27" tracking_level="1" version="0" object_id="_22">
              <id>7</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="27" object_id="_23">
              <id>8</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="27" object_id="_24">
              <id>12</id>
              <stage>20</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_25">
              <id>13</id>
              <stage>20</stage>
              <latency>20</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="25" object_id="_26">
          <id>2</id>
          <operations>
            <count>2</count>
            <item_version>0</item_version>
            <item class_id_reference="27" object_id="_27">
              <id>12</id>
              <stage>19</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_28">
              <id>13</id>
              <stage>19</stage>
              <latency>20</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="25" object_id="_29">
          <id>3</id>
          <operations>
            <count>2</count>
            <item_version>0</item_version>
            <item class_id_reference="27" object_id="_30">
              <id>12</id>
              <stage>18</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_31">
              <id>13</id>
              <stage>18</stage>
              <latency>20</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="25" object_id="_32">
          <id>4</id>
          <operations>
            <count>2</count>
            <item_version>0</item_version>
            <item class_id_reference="27" object_id="_33">
              <id>12</id>
              <stage>17</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_34">
              <id>13</id>
              <stage>17</stage>
              <latency>20</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="25" object_id="_35">
          <id>5</id>
          <operations>
            <count>2</count>
            <item_version>0</item_version>
            <item class_id_reference="27" object_id="_36">
              <id>12</id>
              <stage>16</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_37">
              <id>13</id>
              <stage>16</stage>
              <latency>20</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="25" object_id="_38">
          <id>6</id>
          <operations>
            <count>2</count>
            <item_version>0</item_version>
            <item class_id_reference="27" object_id="_39">
              <id>12</id>
              <stage>15</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_40">
              <id>13</id>
              <stage>15</stage>
              <latency>20</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="25" object_id="_41">
          <id>7</id>
          <operations>
            <count>2</count>
            <item_version>0</item_version>
            <item class_id_reference="27" object_id="_42">
              <id>12</id>
              <stage>14</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_43">
              <id>13</id>
              <stage>14</stage>
              <latency>20</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="25" object_id="_44">
          <id>8</id>
          <operations>
            <count>2</count>
            <item_version>0</item_version>
            <item class_id_reference="27" object_id="_45">
              <id>12</id>
              <stage>13</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_46">
              <id>13</id>
              <stage>13</stage>
              <latency>20</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="25" object_id="_47">
          <id>9</id>
          <operations>
            <count>2</count>
            <item_version>0</item_version>
            <item class_id_reference="27" object_id="_48">
              <id>12</id>
              <stage>12</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_49">
              <id>13</id>
              <stage>12</stage>
              <latency>20</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="25" object_id="_50">
          <id>10</id>
          <operations>
            <count>2</count>
            <item_version>0</item_version>
            <item class_id_reference="27" object_id="_51">
              <id>12</id>
              <stage>11</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_52">
              <id>13</id>
              <stage>11</stage>
              <latency>20</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="25" object_id="_53">
          <id>11</id>
          <operations>
            <count>2</count>
            <item_version>0</item_version>
            <item class_id_reference="27" object_id="_54">
              <id>12</id>
              <stage>10</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_55">
              <id>13</id>
              <stage>10</stage>
              <latency>20</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="25" object_id="_56">
          <id>12</id>
          <operations>
            <count>2</count>
            <item_version>0</item_version>
            <item class_id_reference="27" object_id="_57">
              <id>12</id>
              <stage>9</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_58">
              <id>13</id>
              <stage>9</stage>
              <latency>20</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="25" object_id="_59">
          <id>13</id>
          <operations>
            <count>2</count>
            <item_version>0</item_version>
            <item class_id_reference="27" object_id="_60">
              <id>12</id>
              <stage>8</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_61">
              <id>13</id>
              <stage>8</stage>
              <latency>20</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="25" object_id="_62">
          <id>14</id>
          <operations>
            <count>2</count>
            <item_version>0</item_version>
            <item class_id_reference="27" object_id="_63">
              <id>12</id>
              <stage>7</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_64">
              <id>13</id>
              <stage>7</stage>
              <latency>20</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="25" object_id="_65">
          <id>15</id>
          <operations>
            <count>2</count>
            <item_version>0</item_version>
            <item class_id_reference="27" object_id="_66">
              <id>12</id>
              <stage>6</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_67">
              <id>13</id>
              <stage>6</stage>
              <latency>20</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="25" object_id="_68">
          <id>16</id>
          <operations>
            <count>2</count>
            <item_version>0</item_version>
            <item class_id_reference="27" object_id="_69">
              <id>12</id>
              <stage>5</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_70">
              <id>13</id>
              <stage>5</stage>
              <latency>20</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="25" object_id="_71">
          <id>17</id>
          <operations>
            <count>2</count>
            <item_version>0</item_version>
            <item class_id_reference="27" object_id="_72">
              <id>12</id>
              <stage>4</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_73">
              <id>13</id>
              <stage>4</stage>
              <latency>20</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="25" object_id="_74">
          <id>18</id>
          <operations>
            <count>2</count>
            <item_version>0</item_version>
            <item class_id_reference="27" object_id="_75">
              <id>12</id>
              <stage>3</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_76">
              <id>13</id>
              <stage>3</stage>
              <latency>20</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="25" object_id="_77">
          <id>19</id>
          <operations>
            <count>2</count>
            <item_version>0</item_version>
            <item class_id_reference="27" object_id="_78">
              <id>12</id>
              <stage>2</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_79">
              <id>13</id>
              <stage>2</stage>
              <latency>20</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="25" object_id="_80">
          <id>20</id>
          <operations>
            <count>11</count>
            <item_version>0</item_version>
            <item class_id_reference="27" object_id="_81">
              <id>3</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="27" object_id="_82">
              <id>4</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="27" object_id="_83">
              <id>5</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="27" object_id="_84">
              <id>6</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="27" object_id="_85">
              <id>9</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="27" object_id="_86">
              <id>10</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="27" object_id="_87">
              <id>11</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="27" object_id="_88">
              <id>12</id>
              <stage>1</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_89">
              <id>13</id>
              <stage>1</stage>
              <latency>20</latency>
            </item>
            <item class_id_reference="27" object_id="_90">
              <id>14</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="27" object_id="_91">
              <id>15</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
      </states>
      <transitions class_id="28" tracking_level="0" version="0">
        <count>19</count>
        <item_version>0</item_version>
        <item class_id="29" tracking_level="1" version="0" object_id="_92">
          <inState>1</inState>
          <outState>2</outState>
          <condition class_id="30" tracking_level="0" version="0">
            <id>-1</id>
            <sop class_id="31" tracking_level="0" version="0">
              <count>1</count>
              <item_version>0</item_version>
              <item class_id="32" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="29" object_id="_93">
          <inState>2</inState>
          <outState>3</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="29" object_id="_94">
          <inState>3</inState>
          <outState>4</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="29" object_id="_95">
          <inState>4</inState>
          <outState>5</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="29" object_id="_96">
          <inState>5</inState>
          <outState>6</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="29" object_id="_97">
          <inState>6</inState>
          <outState>7</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="29" object_id="_98">
          <inState>7</inState>
          <outState>8</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="29" object_id="_99">
          <inState>8</inState>
          <outState>9</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="29" object_id="_100">
          <inState>9</inState>
          <outState>10</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="29" object_id="_101">
          <inState>10</inState>
          <outState>11</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="29" object_id="_102">
          <inState>11</inState>
          <outState>12</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="29" object_id="_103">
          <inState>12</inState>
          <outState>13</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="29" object_id="_104">
          <inState>13</inState>
          <outState>14</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="29" object_id="_105">
          <inState>14</inState>
          <outState>15</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="29" object_id="_106">
          <inState>15</inState>
          <outState>16</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="29" object_id="_107">
          <inState>16</inState>
          <outState>17</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="29" object_id="_108">
          <inState>17</inState>
          <outState>18</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="29" object_id="_109">
          <inState>18</inState>
          <outState>19</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="29" object_id="_110">
          <inState>19</inState>
          <outState>20</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
      </transitions>
    </fsm>
    <res class_id="33" tracking_level="1" version="0" object_id="_111">
      <dp_component_resource class_id="34" tracking_level="0" version="0">
        <count>3</count>
        <item_version>0</item_version>
        <item class_id="35" tracking_level="0" version="0">
          <first>hls_divider_CRTLS_s_axi_U (hls_divider_CRTLS_s_axi)</first>
          <second class_id="36" tracking_level="0" version="0">
            <count>3</count>
            <item_version>0</item_version>
            <item class_id="37" tracking_level="0" version="0">
              <first>BRAM</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>112</second>
            </item>
            <item>
              <first>LUT</first>
              <second>168</second>
            </item>
          </second>
        </item>
        <item>
          <first>hls_divider_udiv_bkb_U1 (hls_divider_udiv_bkb)</first>
          <second>
            <count>2</count>
            <item_version>0</item_version>
            <item>
              <first>FF</first>
              <second>202</second>
            </item>
            <item>
              <first>LUT</first>
              <second>123</second>
            </item>
          </second>
        </item>
        <item>
          <first>hls_divider_urem_cud_U2 (hls_divider_urem_cud)</first>
          <second>
            <count>2</count>
            <item_version>0</item_version>
            <item>
              <first>FF</first>
              <second>202</second>
            </item>
            <item>
              <first>LUT</first>
              <second>123</second>
            </item>
          </second>
        </item>
      </dp_component_resource>
      <dp_expression_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_expression_resource>
      <dp_fifo_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_resource>
      <dp_memory_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_resource>
      <dp_multiplexer_resource>
        <count>1</count>
        <item_version>0</item_version>
        <item>
          <first>ap_NS_fsm</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>21</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>21</second>
            </item>
            <item>
              <first>LUT</first>
              <second>101</second>
            </item>
          </second>
        </item>
      </dp_multiplexer_resource>
      <dp_register_resource>
        <count>1</count>
        <item_version>0</item_version>
        <item>
          <first>ap_CS_fsm</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>20</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>20</second>
            </item>
          </second>
        </item>
      </dp_register_resource>
      <dp_dsp_resource>
        <count>3</count>
        <item_version>0</item_version>
        <item>
          <first>hls_divider_CRTLS_s_axi_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>hls_divider_udiv_bkb_U1</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>hls_divider_urem_cud_U2</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
      </dp_dsp_resource>
      <dp_component_map class_id="38" tracking_level="0" version="0">
        <count>2</count>
        <item_version>0</item_version>
        <item class_id="39" tracking_level="0" version="0">
          <first>hls_divider_udiv_bkb_U1 (hls_divider_udiv_bkb)</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>12</item>
          </second>
        </item>
        <item>
          <first>hls_divider_urem_cud_U2 (hls_divider_urem_cud)</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>13</item>
          </second>
        </item>
      </dp_component_map>
      <dp_expression_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_expression_map>
      <dp_fifo_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_map>
      <dp_memory_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_map>
    </res>
    <node_label_latency class_id="40" tracking_level="0" version="0">
      <count>6</count>
      <item_version>0</item_version>
      <item class_id="41" tracking_level="0" version="0">
        <first>7</first>
        <second class_id="42" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>8</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>12</first>
        <second>
          <first>0</first>
          <second>19</second>
        </second>
      </item>
      <item>
        <first>13</first>
        <second>
          <first>0</first>
          <second>19</second>
        </second>
      </item>
      <item>
        <first>14</first>
        <second>
          <first>19</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>15</first>
        <second>
          <first>19</first>
          <second>0</second>
        </second>
      </item>
    </node_label_latency>
    <bblk_ent_exit class_id="43" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="44" tracking_level="0" version="0">
        <first>16</first>
        <second class_id="45" tracking_level="0" version="0">
          <first>0</first>
          <second>19</second>
        </second>
      </item>
    </bblk_ent_exit>
    <regions class_id="46" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </regions>
    <dp_fu_nodes class_id="47" tracking_level="0" version="0">
      <count>5</count>
      <item_version>0</item_version>
      <item class_id="48" tracking_level="0" version="0">
        <first>24</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>7</item>
        </second>
      </item>
      <item>
        <first>30</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
      <item>
        <first>36</first>
        <second>
          <count>20</count>
          <item_version>0</item_version>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
        </second>
      </item>
      <item>
        <first>42</first>
        <second>
          <count>20</count>
          <item_version>0</item_version>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
        </second>
      </item>
      <item>
        <first>48</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>14</item>
        </second>
      </item>
    </dp_fu_nodes>
    <dp_fu_nodes_expression class_id="50" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="51" tracking_level="0" version="0">
        <first>r_fu_48</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>14</item>
        </second>
      </item>
    </dp_fu_nodes_expression>
    <dp_fu_nodes_module>
      <count>2</count>
      <item_version>0</item_version>
      <item>
        <first>grp_fu_36</first>
        <second>
          <count>20</count>
          <item_version>0</item_version>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
          <item>12</item>
        </second>
      </item>
      <item>
        <first>grp_fu_42</first>
        <second>
          <count>20</count>
          <item_version>0</item_version>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
          <item>13</item>
        </second>
      </item>
    </dp_fu_nodes_module>
    <dp_fu_nodes_io>
      <count>2</count>
      <item_version>0</item_version>
      <item>
        <first>a_read_read_fu_30</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
      <item>
        <first>b_read_read_fu_24</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>7</item>
        </second>
      </item>
    </dp_fu_nodes_io>
    <return_ports>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>ap_return</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>15</item>
        </second>
      </item>
    </return_ports>
    <dp_mem_port_nodes class_id="52" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </dp_mem_port_nodes>
    <dp_reg_nodes>
      <count>2</count>
      <item_version>0</item_version>
      <item>
        <first>56</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>7</item>
        </second>
      </item>
      <item>
        <first>62</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
    </dp_reg_nodes>
    <dp_regname_nodes>
      <count>2</count>
      <item_version>0</item_version>
      <item>
        <first>a_read_reg_62</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
      <item>
        <first>b_read_reg_56</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>7</item>
        </second>
      </item>
    </dp_regname_nodes>
    <dp_reg_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_reg_phi>
    <dp_regname_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_regname_phi>
    <dp_port_io_nodes class_id="53" tracking_level="0" version="0">
      <count>2</count>
      <item_version>0</item_version>
      <item class_id="54" tracking_level="0" version="0">
        <first>a</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>read</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>8</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>b</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>read</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>7</item>
            </second>
          </item>
        </second>
      </item>
    </dp_port_io_nodes>
    <port2core class_id="55" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </port2core>
    <node2core>
      <count>0</count>
      <item_version>0</item_version>
    </node2core>
  </syndb>
</boost_serialization>
