# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGAJosieVivian/ZynqComputerExtended/ZynqComputer.srcs/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_hls_multiplier_0_0/Zynq_CPU_hls_multiplier_0_0.xci
# IP: The module: 'Zynq_CPU_hls_multiplier_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGAJosieVivian/ZynqComputerExtended/ZynqComputer.srcs/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_hls_multiplier_0_0/constraints/hls_multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_CPU_hls_multiplier_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/FPGAJosieVivian/ZynqComputerExtended/ZynqComputer.srcs/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_hls_multiplier_0_0/Zynq_CPU_hls_multiplier_0_0.xci
# IP: The module: 'Zynq_CPU_hls_multiplier_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGAJosieVivian/ZynqComputerExtended/ZynqComputer.srcs/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_hls_multiplier_0_0/constraints/hls_multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_CPU_hls_multiplier_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
