// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "hls_multiplier.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic hls_multiplier::ap_const_logic_1 = sc_dt::Log_1;
const int hls_multiplier::C_S_AXI_DATA_WIDTH = "100000";
const bool hls_multiplier::ap_const_boolean_1 = true;
const sc_logic hls_multiplier::ap_const_logic_0 = sc_dt::Log_0;

hls_multiplier::hls_multiplier(sc_module_name name) : sc_module(name), mVcdFile(0) {
    hls_multiplier_CRTLS_s_axi_U = new hls_multiplier_CRTLS_s_axi<C_S_AXI_CRTLS_ADDR_WIDTH,C_S_AXI_CRTLS_DATA_WIDTH>("hls_multiplier_CRTLS_s_axi_U");
    hls_multiplier_CRTLS_s_axi_U->AWVALID(s_axi_CRTLS_AWVALID);
    hls_multiplier_CRTLS_s_axi_U->AWREADY(s_axi_CRTLS_AWREADY);
    hls_multiplier_CRTLS_s_axi_U->AWADDR(s_axi_CRTLS_AWADDR);
    hls_multiplier_CRTLS_s_axi_U->WVALID(s_axi_CRTLS_WVALID);
    hls_multiplier_CRTLS_s_axi_U->WREADY(s_axi_CRTLS_WREADY);
    hls_multiplier_CRTLS_s_axi_U->WDATA(s_axi_CRTLS_WDATA);
    hls_multiplier_CRTLS_s_axi_U->WSTRB(s_axi_CRTLS_WSTRB);
    hls_multiplier_CRTLS_s_axi_U->ARVALID(s_axi_CRTLS_ARVALID);
    hls_multiplier_CRTLS_s_axi_U->ARREADY(s_axi_CRTLS_ARREADY);
    hls_multiplier_CRTLS_s_axi_U->ARADDR(s_axi_CRTLS_ARADDR);
    hls_multiplier_CRTLS_s_axi_U->RVALID(s_axi_CRTLS_RVALID);
    hls_multiplier_CRTLS_s_axi_U->RREADY(s_axi_CRTLS_RREADY);
    hls_multiplier_CRTLS_s_axi_U->RDATA(s_axi_CRTLS_RDATA);
    hls_multiplier_CRTLS_s_axi_U->RRESP(s_axi_CRTLS_RRESP);
    hls_multiplier_CRTLS_s_axi_U->BVALID(s_axi_CRTLS_BVALID);
    hls_multiplier_CRTLS_s_axi_U->BREADY(s_axi_CRTLS_BREADY);
    hls_multiplier_CRTLS_s_axi_U->BRESP(s_axi_CRTLS_BRESP);
    hls_multiplier_CRTLS_s_axi_U->ACLK(ap_clk);
    hls_multiplier_CRTLS_s_axi_U->ARESET(ap_rst_n_inv);
    hls_multiplier_CRTLS_s_axi_U->ACLK_EN(ap_var_for_const0);
    hls_multiplier_CRTLS_s_axi_U->ap_start(ap_start);
    hls_multiplier_CRTLS_s_axi_U->interrupt(interrupt);
    hls_multiplier_CRTLS_s_axi_U->ap_ready(ap_ready);
    hls_multiplier_CRTLS_s_axi_U->ap_done(ap_done);
    hls_multiplier_CRTLS_s_axi_U->ap_idle(ap_idle);
    hls_multiplier_CRTLS_s_axi_U->ap_return(p_fu_42_p2);
    hls_multiplier_CRTLS_s_axi_U->a(a);
    hls_multiplier_CRTLS_s_axi_U->b(b);
    hls_multiplier_mubkb_U1 = new hls_multiplier_mubkb<1,1,16,16,32>("hls_multiplier_mubkb_U1");
    hls_multiplier_mubkb_U1->din0(p_fu_42_p0);
    hls_multiplier_mubkb_U1->din1(p_fu_42_p1);
    hls_multiplier_mubkb_U1->dout(p_fu_42_p2);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_p_fu_42_p0);
    sensitive << ( p_fu_42_p00 );

    SC_METHOD(thread_p_fu_42_p00);
    sensitive << ( b );

    SC_METHOD(thread_p_fu_42_p1);
    sensitive << ( p_fu_42_p10 );

    SC_METHOD(thread_p_fu_42_p10);
    sensitive << ( a );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_virtual_clock.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "hls_multiplier_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, s_axi_CRTLS_AWVALID, "(port)s_axi_CRTLS_AWVALID");
    sc_trace(mVcdFile, s_axi_CRTLS_AWREADY, "(port)s_axi_CRTLS_AWREADY");
    sc_trace(mVcdFile, s_axi_CRTLS_AWADDR, "(port)s_axi_CRTLS_AWADDR");
    sc_trace(mVcdFile, s_axi_CRTLS_WVALID, "(port)s_axi_CRTLS_WVALID");
    sc_trace(mVcdFile, s_axi_CRTLS_WREADY, "(port)s_axi_CRTLS_WREADY");
    sc_trace(mVcdFile, s_axi_CRTLS_WDATA, "(port)s_axi_CRTLS_WDATA");
    sc_trace(mVcdFile, s_axi_CRTLS_WSTRB, "(port)s_axi_CRTLS_WSTRB");
    sc_trace(mVcdFile, s_axi_CRTLS_ARVALID, "(port)s_axi_CRTLS_ARVALID");
    sc_trace(mVcdFile, s_axi_CRTLS_ARREADY, "(port)s_axi_CRTLS_ARREADY");
    sc_trace(mVcdFile, s_axi_CRTLS_ARADDR, "(port)s_axi_CRTLS_ARADDR");
    sc_trace(mVcdFile, s_axi_CRTLS_RVALID, "(port)s_axi_CRTLS_RVALID");
    sc_trace(mVcdFile, s_axi_CRTLS_RREADY, "(port)s_axi_CRTLS_RREADY");
    sc_trace(mVcdFile, s_axi_CRTLS_RDATA, "(port)s_axi_CRTLS_RDATA");
    sc_trace(mVcdFile, s_axi_CRTLS_RRESP, "(port)s_axi_CRTLS_RRESP");
    sc_trace(mVcdFile, s_axi_CRTLS_BVALID, "(port)s_axi_CRTLS_BVALID");
    sc_trace(mVcdFile, s_axi_CRTLS_BREADY, "(port)s_axi_CRTLS_BREADY");
    sc_trace(mVcdFile, s_axi_CRTLS_BRESP, "(port)s_axi_CRTLS_BRESP");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, a, "a");
    sc_trace(mVcdFile, b, "b");
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, p_fu_42_p0, "p_fu_42_p0");
    sc_trace(mVcdFile, p_fu_42_p1, "p_fu_42_p1");
    sc_trace(mVcdFile, p_fu_42_p2, "p_fu_42_p2");
    sc_trace(mVcdFile, p_fu_42_p00, "p_fu_42_p00");
    sc_trace(mVcdFile, p_fu_42_p10, "p_fu_42_p10");
    sc_trace(mVcdFile, ap_return, "ap_return");
#endif

    }
    mHdltvinHandle.open("hls_multiplier.hdltvin.dat");
    mHdltvoutHandle.open("hls_multiplier.hdltvout.dat");
}

hls_multiplier::~hls_multiplier() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete hls_multiplier_CRTLS_s_axi_U;
    delete hls_multiplier_mubkb_U1;
}

void hls_multiplier::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void hls_multiplier::thread_ap_done() {
    ap_done = ap_start.read();
}

void hls_multiplier::thread_ap_idle() {
    ap_idle = ap_const_logic_1;
}

void hls_multiplier::thread_ap_ready() {
    ap_ready = ap_start.read();
}

void hls_multiplier::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void hls_multiplier::thread_p_fu_42_p0() {
    p_fu_42_p0 =  (sc_lv<16>) (p_fu_42_p00.read());
}

void hls_multiplier::thread_p_fu_42_p00() {
    p_fu_42_p00 = esl_zext<32,16>(b.read());
}

void hls_multiplier::thread_p_fu_42_p1() {
    p_fu_42_p1 =  (sc_lv<16>) (p_fu_42_p10.read());
}

void hls_multiplier::thread_p_fu_42_p10() {
    p_fu_42_p10 = esl_zext<32,16>(a.read());
}

void hls_multiplier::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"s_axi_CRTLS_AWVALID\" :  \"" << s_axi_CRTLS_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_CRTLS_AWREADY\" :  \"" << s_axi_CRTLS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTLS_AWADDR\" :  \"" << s_axi_CRTLS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTLS_WVALID\" :  \"" << s_axi_CRTLS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTLS_WREADY\" :  \"" << s_axi_CRTLS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTLS_WDATA\" :  \"" << s_axi_CRTLS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTLS_WSTRB\" :  \"" << s_axi_CRTLS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTLS_ARVALID\" :  \"" << s_axi_CRTLS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTLS_ARREADY\" :  \"" << s_axi_CRTLS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTLS_ARADDR\" :  \"" << s_axi_CRTLS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTLS_RVALID\" :  \"" << s_axi_CRTLS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTLS_RREADY\" :  \"" << s_axi_CRTLS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTLS_RDATA\" :  \"" << s_axi_CRTLS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTLS_RRESP\" :  \"" << s_axi_CRTLS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTLS_BVALID\" :  \"" << s_axi_CRTLS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTLS_BREADY\" :  \"" << s_axi_CRTLS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTLS_BRESP\" :  \"" << s_axi_CRTLS_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

