// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _hls_multiplier_HH_
#define _hls_multiplier_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "hls_multiplier_mubkb.h"
#include "hls_multiplier_CRTLS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_CRTLS_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_CRTLS_DATA_WIDTH = 32>
struct hls_multiplier : public sc_module {
    // Port declarations 20
    sc_in< sc_logic > s_axi_CRTLS_AWVALID;
    sc_out< sc_logic > s_axi_CRTLS_AWREADY;
    sc_in< sc_uint<C_S_AXI_CRTLS_ADDR_WIDTH> > s_axi_CRTLS_AWADDR;
    sc_in< sc_logic > s_axi_CRTLS_WVALID;
    sc_out< sc_logic > s_axi_CRTLS_WREADY;
    sc_in< sc_uint<C_S_AXI_CRTLS_DATA_WIDTH> > s_axi_CRTLS_WDATA;
    sc_in< sc_uint<C_S_AXI_CRTLS_DATA_WIDTH/8> > s_axi_CRTLS_WSTRB;
    sc_in< sc_logic > s_axi_CRTLS_ARVALID;
    sc_out< sc_logic > s_axi_CRTLS_ARREADY;
    sc_in< sc_uint<C_S_AXI_CRTLS_ADDR_WIDTH> > s_axi_CRTLS_ARADDR;
    sc_out< sc_logic > s_axi_CRTLS_RVALID;
    sc_in< sc_logic > s_axi_CRTLS_RREADY;
    sc_out< sc_uint<C_S_AXI_CRTLS_DATA_WIDTH> > s_axi_CRTLS_RDATA;
    sc_out< sc_lv<2> > s_axi_CRTLS_RRESP;
    sc_out< sc_logic > s_axi_CRTLS_BVALID;
    sc_in< sc_logic > s_axi_CRTLS_BREADY;
    sc_out< sc_lv<2> > s_axi_CRTLS_BRESP;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    hls_multiplier(sc_module_name name);
    SC_HAS_PROCESS(hls_multiplier);

    ~hls_multiplier();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    hls_multiplier_CRTLS_s_axi<C_S_AXI_CRTLS_ADDR_WIDTH,C_S_AXI_CRTLS_DATA_WIDTH>* hls_multiplier_CRTLS_s_axi_U;
    hls_multiplier_mubkb<1,1,16,16,32>* hls_multiplier_mubkb_U1;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<16> > a;
    sc_signal< sc_lv<16> > b;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<16> > p_fu_42_p0;
    sc_signal< sc_lv<16> > p_fu_42_p1;
    sc_signal< sc_lv<32> > p_fu_42_p2;
    sc_signal< sc_lv<32> > p_fu_42_p00;
    sc_signal< sc_lv<32> > p_fu_42_p10;
    sc_signal< sc_lv<32> > ap_return;
    static const sc_logic ap_const_logic_1;
    static const int C_S_AXI_DATA_WIDTH;
    static const bool ap_const_boolean_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_p_fu_42_p0();
    void thread_p_fu_42_p00();
    void thread_p_fu_42_p1();
    void thread_p_fu_42_p10();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
